### PR TITLE
Fixed bookmarklet

### PR DESCRIPTION
**Pull request by quetzalcoatl82**
Youtube changed the layout and broke the bookmarklet, fixed the menu version and added new video type (AV1)

### CODE REVIEW

**Comment by minanagehsalalma** [comment]
@quetzalcoatl82 thanks tremendously dude for paying attention and taking time to fix it .. ❤

**Comment by minanagehsalalma** [comment]
@quetzalcoatl82 are you available for a new feature collab ?

**Comment by quetzalcoatl82** [comment]
Hi @minanagehsalalma, what do you have in mind?

**Comment by minanagehsalalma** [comment]
@quetzalcoatl82 do u have discord or something to discuss it? 

i am thinking about fusing without actually transcoding the webm vid + audio into one ... so we go behind the current YouTube blocker problem .... as these formats play directly in the browser.

**Comment by quetzalcoatl82** [comment]
Sorry, I can't help you with this feature.

**Pull request merged**
